services:
  - type: web
    name: play-infinity
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production

  # Cron Job para evitar que o Web Service principal (Free Tier) durma
  - type: cron
    name: ping-keep-alive
    env: node
    plan: free
    schedule: "*/10 * * * *" # Executa a cada 10 minutos conforme configurado anteriormente
    buildCommand: ""
    startCommand: "curl -f https://play-infinity-app.onrender.com/api/health || exit 0"
