export type CatalogItem = {
  id: number;
  tmdbId?: number;
  imdbId?: string;
  title: string;
  imageUrl: string;
  posterUrl?: string;
  backdropUrl?: string;
  type: 'movie' | 'series';
  genres: string[];
  synopsis?: string;
  year?: number;
  rating?: string;
  duration?: string;
  match?: number;
  playerUrl?: string;
  quality?: 'CAM' | 'TS' | 'HD' | '4K' | 'FULL HD';
  provider?: string;
};

/** Verifica se um item possui qualidade CAM (gravação de cinema) */
export function checkIsCam(title?: string, quality?: string): boolean {
  if (quality === 'CAM' || quality === 'TS') return true;
  if (!title) return false;
  const upper = title.toUpperCase();
  if (upper.includes('CAM') || upper.includes('CINEMA') || upper.includes('TS')) return true;
  if (upper.includes('HOMEM-ARANHA: UM NOVO DIA') || upper.includes('HOMEM-ARANHA 4')) return true;
  return false;
}

export const featured = {
  id: 969681,
  tmdbId: 969681,
  imdbId: "tt22084616",
  title: "HOMEM-ARANHA: UM NOVO DIA",
  year: "2026",
  duration: "2h 23min",
  rating: 4.9,
  quality: "CAM" as const,
  genres: ["Ação", "Aventura", "Ficção científica"],
  description:
    "Peter Parker enfrenta um novo capítulo em sua vida após os eventos mundiais. Sem suas antigas memórias com seus entes queridos, uma nova ameaça surge em Nova York, forçando o herói a equilibrar o fardo de sua responsabilidade com novos aliados e perigos inimagináveis.",
  imageUrl:
    "https://image.tmdb.org/t/p/original/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg",
  posterUrl:
    "https://image.tmdb.org/t/p/w500/x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpg",
  logoText: "HOMEM-ARANHA\nUM NOVO DIA",
  playerUrl: "https://v1.watchplay.shop/movie/tt22084616",
};

export const providers = [
  "NETFLIX",
  "Disney+",
  "Max",
  "Prime Video",
  "Apple TV+",
  "Globoplay",
];

export const continueWatching = [
  {
    id: 66732,
    tmdbId: 66732,
    imdbId: "tt4574334",
    title: "STRANGER THINGS",
    episode: "T4:E1 - O Clube Hellfire",
    progress: 75,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    playerUrl: "https://v1.watchplay.shop/tvshow/66732/4/1",
  },
  {
    id: 533535,
    tmdbId: 533535,
    title: "DEADPOOL & WOLVERINE",
    episode: "Continuar do min 45",
    progress: 42,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/533535",
  },
];

export const top10 = [
  {
    id: 969681,
    tmdbId: 969681,
    imdbId: "tt22084616",
    title: "HOMEM-ARANHA: UM NOVO DIA",
    quality: "CAM" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/tt22084616",
  },
  {
    id: 533535,
    tmdbId: 533535,
    title: "DEADPOOL & WOLVERINE",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/cJFqqiDYprqExaXatu4AaoMzDG2.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/533535",
  },
  {
    id: 693134,
    tmdbId: 693134,
    title: "DUNA: PARTE DOIS",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/hH5lhwd8RzvVGbpRixPvIOltZLt.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/693134",
  },
  {
    id: 1022789,
    tmdbId: 1022789,
    title: "DIVERTIDA MENTE 2",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/lHKNS35r4RTa9GO72vdadMLxoiV.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/1022789",
  },
  {
    id: 94997,
    tmdbId: 94997,
    title: "A CASA DO DRAGÃO",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/oKJDm4QCKbp6mR4FnxXrFlPJP8Y.jpg",
    playerUrl: "https://v1.watchplay.shop/tvshow/94997/1/1",
  },
];

export const releases = [
  {
    id: 969681,
    tmdbId: 969681,
    title: "HOMEM-ARANHA: UM NOVO DIA",
    quality: "CAM" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/tt22084616",
  },
  {
    id: 533535,
    tmdbId: 533535,
    title: "DEADPOOL & WOLVERINE",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/cJFqqiDYprqExaXatu4AaoMzDG2.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/533535",
  },
  {
    id: 693134,
    tmdbId: 693134,
    title: "DUNA: PARTE DOIS",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/8LJJjLjAzAwXS40S5mx79PJ2jSs.jpg",
    playerUrl: "https://v1.watchplay.shop/movie/693134",
  },
];

export const newest = [
  {
    id: 125988,
    tmdbId: 125988,
    title: "SILO",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/tVR4q9FazxJuCEpaYxiCijUlvM3.jpg",
    playerUrl: "https://v1.watchplay.shop/tvshow/125988/1/1",
  },
  {
    id: 76479,
    tmdbId: 76479,
    title: "THE BOYS",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/in1R2dDc421JxsoRWaIIAqVI2KE.jpg",
    playerUrl: "https://v1.watchplay.shop/tvshow/76479/1/1",
  },
  {
    id: 100088,
    tmdbId: 100088,
    title: "THE LAST OF US",
    imageUrl:
      "https://image.tmdb.org/t/p/w500/el1KQzwdIm17I3A6cYPfsVIWhfX.jpg",
    playerUrl: "https://v1.watchplay.shop/tvshow/100088/1/1",
  },
];

export const mostWatched = [
  {
    id: 299534,
    tmdbId: 299534,
    title: "VINGADORES: ULTIMATO",
    type: "movie" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/9fRX8UKlIW7Lb9GqNsJVakWWFCi.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/movie/299534",
  },
  {
    id: 66732,
    tmdbId: 66732,
    imdbId: "tt4574334",
    title: "STRANGER THINGS",
    type: "series" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/twfKp60THrcOIep9sjHODOOfO8d.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/tvshow/66732/1/1",
  },
  {
    id: 533535,
    tmdbId: 533535,
    title: "DEADPOOL & WOLVERINE",
    type: "movie" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/cJFqqiDYprqExaXatu4AaoMzDG2.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/movie/533535",
  },
  {
    id: 93405,
    tmdbId: 93405,
    title: "ROUND 6 (SQUID GAME)",
    type: "series" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/6gcHdboppvplmBWxvROc96NJnmm.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/tvshow/93405/1/1",
  },
  {
    id: 969681,
    tmdbId: 969681,
    imdbId: "tt22084616",
    title: "HOMEM-ARANHA: UM NOVO DIA",
    type: "movie" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg",
    quality: "CAM" as const,
    playerUrl: "https://v1.watchplay.shop/movie/tt22084616",
  },
  {
    id: 119051,
    tmdbId: 119051,
    title: "WANDINHA",
    type: "series" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/7rxiQrZjrer0RB9qNA8rHYFo53R.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/tvshow/119051/1/1",
  },
  {
    id: 157336,
    tmdbId: 157336,
    title: "INTERESTELAR",
    type: "movie" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/gEU2QniE6EwfVDxCzsxPnZLi1ZT.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/rAiYTsqJiOkn00e21jS1vQhYyY.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/movie/157336",
  },
  {
    id: 100088,
    tmdbId: 100088,
    title: "THE LAST OF US",
    type: "series" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/el1KQzwdIm17I3A6cYPfsVIWhfX.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/tvshow/100088/1/1",
  },
  {
    id: 1022789,
    tmdbId: 1022789,
    title: "DIVERTIDA MENTE 2",
    type: "movie" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/lHKNS35r4RTa9GO72vdadMLxoiV.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/stKGOmbuwhL489ZJnZUVvA34Dt.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/movie/1022789",
  },
  {
    id: 94997,
    tmdbId: 94997,
    title: "A CASA DO DRAGÃO",
    type: "series" as const,
    imageUrl:
      "https://image.tmdb.org/t/p/w500/oKJDm4QCKbp6mR4FnxXrFlPJP8Y.jpg",
    backdropUrl:
      "https://image.tmdb.org/t/p/original/etjA24UepnNnLh2t9qjU2Vj2g3g.jpg",
    quality: "HD" as const,
    playerUrl: "https://v1.watchplay.shop/tvshow/94997/1/1",
  },
];

export const providerCatalogs: Record<string, CatalogItem[]> = {
  "NETFLIX": [
    {
      id: 66732,
      tmdbId: 66732,
      imdbId: "tt4574334",
      title: "STRANGER THINGS",
      imageUrl: "https://image.tmdb.org/t/p/w500/twfKp60THrcOIep9sjHODOOfO8d.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
      type: "series",
      genres: ["Ficção Científica", "Drama", "Mistério"],
      synopsis: "Quando um garoto desaparece, uma pequena cidade descobre um mistério envolvendo experimentos secretos, forças sobrenaturais aterrorizantes e uma garota com poderes telecinéticos.",
      year: 2024,
      rating: "16",
      duration: "4 Temporadas",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/tvshow/66732/1/1",
    },
    {
      id: 119051,
      tmdbId: 119051,
      title: "WANDINHA",
      imageUrl: "https://image.tmdb.org/t/p/w500/7rxiQrZjrer0RB9qNA8rHYFo53R.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
      type: "series",
      genres: ["Comédia", "Fantasia", "Mistério"],
      synopsis: "Inteligente, sarcástica e um pouco apática, Wandinha Addams investiga uma onda de assassinatos enquanto faz novos amigos — e inimigos — na Academia Nunca Mais.",
      year: 2023,
      rating: "14",
      duration: "1 Temporada",
      match: 96,
      playerUrl: "https://v1.watchplay.shop/tvshow/119051/1/1",
    },
    {
      id: 93405,
      tmdbId: 93405,
      title: "ROUND 6 (SQUID GAME)",
      imageUrl: "https://image.tmdb.org/t/p/w500/6gcHdboppvplmBWxvROc96NJnmm.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/2meX1nMdScFOoV4370rqHWKmXhY.jpg",
      type: "series",
      genres: ["Ação", "Mistério", "Drama"],
      synopsis: "Centenas de jogadores falidos aceitam um estranho convite para competir em jogos infantis por um prêmio tentador, mas as consequências são mortais.",
      year: 2024,
      rating: "18",
      duration: "2 Temporadas",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/93405/1/1",
    },
    {
      id: 71446,
      tmdbId: 71446,
      title: "LA CASA DE PAPEL",
      imageUrl: "https://image.tmdb.org/t/p/w500/UfXcC5GbCCMPW2qZ3SB8D9hpUz.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/gFZriCkpJYsApPZEF3jhxL4yLzG.jpg",
      type: "series",
      genres: ["Crime", "Drama", "Ação"],
      synopsis: "Oito ladrões se trancam com reféns na Casa da Moeda da Espanha com o plano de realizar o maior assalto da história sob o comando do misterioso Professor.",
      year: 2021,
      rating: "16",
      duration: "5 Temporadas",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/tvshow/71446/1/1",
    },
    {
      id: 94605,
      tmdbId: 94605,
      title: "ARCANE",
      imageUrl: "https://image.tmdb.org/t/p/w500/m3Tzf6k537PnhOEwaSRNCSxedLS.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/5cvnxEHT3e39DvT6ARw4GNCFrB0.jpg",
      type: "series",
      genres: ["Animação", "Ficção Científica", "Ação"],
      synopsis: "Em meio ao conflito entre as cidades-gêmeas de Piltover e Zaun, duas irmãs lutam em lados opostos de uma guerra entre tecnologias mágicas e convicções incompatíveis.",
      year: 2024,
      rating: "16",
      duration: "2 Temporadas",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/tvshow/94605/1/1",
    },
    {
      id: 87739,
      tmdbId: 87739,
      title: "O GAMBITO DA RAINHA",
      imageUrl: "https://image.tmdb.org/t/p/w500/ubWpLTkwcms5PfZJMFZkNXVYXqJ.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/34OGjFEbHj0E3lE2w0iTUVq0CBz.jpg",
      type: "series",
      genres: ["Drama"],
      synopsis: "Em um orfanato nos anos 1950, uma garota prodígio descobre um talento surpreendente para o xadrez, enquanto enfrenta o vício e os limites da genialidade.",
      year: 2020,
      rating: "16",
      duration: "Minissérie",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/87739/1/1",
    },
    {
      id: 60574,
      tmdbId: 60574,
      title: "PEAKY BLINDERS",
      imageUrl: "https://image.tmdb.org/t/p/w500/i0uajcHH9yogXMfDHpOXexIukG9.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/dzq83RHwQcnP6WGJ6YkenIqeaa5.jpg",
      type: "series",
      genres: ["Crime", "Drama"],
      synopsis: "Uma notória gangue da Inglaterra de 1919 é liderada pelo feroz Tommy Shelby, um criminoso disposto a subir no mundo a qualquer preço.",
      year: 2022,
      rating: "18",
      duration: "6 Temporadas",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/60574/1/1",
    },
    {
      id: 70523,
      tmdbId: 70523,
      title: "DARK",
      imageUrl: "https://image.tmdb.org/t/p/w500/wiiyc3m6HKaQhFBYeuM7ySCNQsG.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/3jDXL4Xvj3AzDOF6UH1xeyHW8MH.jpg",
      type: "series",
      genres: ["Ficção Científica", "Mistério", "Drama"],
      synopsis: "O desaparecimento de duas crianças em uma cidade alemã expõe a vida dupla e os relacionamentos fragmentados entre quatro famílias ao longo de gerações.",
      year: 2020,
      rating: "16",
      duration: "3 Temporadas",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/tvshow/70523/1/1",
    },
    {
      id: 65495,
      tmdbId: 65495,
      title: "THE CROWN",
      imageUrl: "https://image.tmdb.org/t/p/w500/8HZyGMnPLVVb00rmrh6A2SbK9NX.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/vN84JlTvOZvZzxi0D2SJQNFvtjS.jpg",
      type: "series",
      genres: ["Drama", "História"],
      synopsis: "Esta série dramática segue a política, rivalidades e relacionamentos da rainha Elizabeth II e os eventos que moldaram a segunda metade do século XX.",
      year: 2023,
      rating: "16",
      duration: "6 Temporadas",
      match: 96,
      playerUrl: "https://v1.watchplay.shop/tvshow/65495/1/1",
    },
    {
      id: 108978,
      tmdbId: 108978,
      title: "BRIDGERTON",
      imageUrl: "https://image.tmdb.org/t/p/w500/f1VCQIG2iCyOookdgOzwtUpwWC0.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/pF0qkRsrHkdYadPWY9AMeFZfcwk.jpg",
      type: "series",
      genres: ["Drama", "Romance"],
      synopsis: "Oito irmãos inseparáveis da família Bridgerton buscam o amor e a felicidade na alta sociedade de Londres.",
      year: 2024,
      rating: "16",
      duration: "3 Temporadas",
      match: 95,
      playerUrl: "https://v1.watchplay.shop/tvshow/108978/1/1",
    }
  ],
  "Disney+": [
    {
      id: 82856,
      tmdbId: 82856,
      title: "THE MANDALORIAN",
      imageUrl: "https://image.tmdb.org/t/p/w500/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/9zcbqSxdsRMZWHYtyCd1nXPr2xq.jpg",
      type: "series",
      genres: ["Ficção Científica", "Ação", "Aventura"],
      synopsis: "Após a queda do Império Galáctico, um solitário pistoleiro mandaloriano viaja pelos confins da galáxia, longe da autoridade da Nova República.",
      year: 2023,
      rating: "12",
      duration: "3 Temporadas",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/tvshow/82856/1/1",
    },
    {
      id: 84958,
      tmdbId: 84958,
      title: "LOKI",
      imageUrl: "https://image.tmdb.org/t/p/w500/2TwPJfPiBI2lVrofggw3H0b4cDC.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/q3jHCb4dMfYF6ojikKuHd6LscxC.jpg",
      type: "series",
      genres: ["Ficção Científica", "Fantasia", "Aventura"],
      synopsis: "O volúvel vilão Loki retoma seu papel como o Deus da Trapaça em uma série que se passa após os acontecimentos de Vingadores: Ultimato.",
      year: 2023,
      rating: "14",
      duration: "2 Temporadas",
      match: 96,
      playerUrl: "https://v1.watchplay.shop/tvshow/84958/1/1",
    },
    {
      id: 85271,
      tmdbId: 85271,
      title: "WANDAVISION",
      imageUrl: "https://image.tmdb.org/t/p/w500/8mAyDNSCZDiejPTm4lwgbztut7y.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/lOr9NKxh4vMweufMOUDJjJhCRHW.jpg",
      type: "series",
      genres: ["Ficção Científica", "Mistério", "Drama"],
      synopsis: "Wanda Maximoff e Visão vivem uma vida suburbana idealizada, até que começam a suspeitar que as coisas não são o que parecem.",
      year: 2021,
      rating: "14",
      duration: "1 Temporada",
      match: 95,
      playerUrl: "https://v1.watchplay.shop/tvshow/85271/1/1",
    },
    {
      id: 92782,
      tmdbId: 92782,
      title: "MS. MARVEL",
      imageUrl: "https://image.tmdb.org/t/p/w500/8Rzkt43GnMyTN0srvn3Z4u7C7VU.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/mfcLUWASJghU8MTNK38eYktfE83.jpg",
      type: "series",
      genres: ["Ação", "Comédia", "Aventura"],
      synopsis: "Kamala Khan, uma adolescente muçulmana americana em Jersey City, é uma jogadora ávida e uma escritora voraz de fan-fiction com grande imaginação.",
      year: 2022,
      rating: "12",
      duration: "1 Temporada",
      match: 90,
      playerUrl: "https://v1.watchplay.shop/tvshow/92782/1/1",
    },
    {
      id: 88396,
      tmdbId: 88396,
      title: "FALCÃO E O SOLDADO INVERNAL",
      imageUrl: "https://image.tmdb.org/t/p/w500/oF9njYCN6lBdrsi6wfulcxTggvn.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/aTjbqMONy77fHJrIYu14g1F0d5h.jpg",
      type: "series",
      genres: ["Ação", "Aventura", "Drama"],
      synopsis: "Sam Wilson e Bucky Barnes se unem em uma aventura global que testará suas habilidades — e sua paciência.",
      year: 2021,
      rating: "14",
      duration: "1 Temporada",
      match: 92,
      playerUrl: "https://v1.watchplay.shop/tvshow/88396/1/1",
    },
    {
      id: 969681,
      tmdbId: 969681,
      imdbId: "tt22084616",
      title: "HOMEM-ARANHA: UM NOVO DIA",
      quality: "CAM" as const,
      imageUrl: "https://image.tmdb.org/t/p/w500/x0nvYzQpyJc5pdT9lMnkMuYAg0O.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/qeQJx07rK2xm8SD2sJxFKhE7gs0.jpg",
      type: "movie",
      genres: ["Ação", "Aventura", "Ficção científica"],
      synopsis: "Peter Parker enfrenta um novo capítulo em sua vida após os eventos mundiais. Sem suas antigas memórias com seus entes queridos, uma nova ameaça surge em Nova York.",
      year: 2026,
      rating: "14",
      duration: "2h 23m",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/movie/tt22084616",
    },
    {
      id: 533535,
      tmdbId: 533535,
      title: "DEADPOOL & WOLVERINE",
      imageUrl: "https://image.tmdb.org/t/p/w500/cJFqqiDYprqExaXatu4AaoMzDG2.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/by8z9Fe8y7p4jo2YlW2SZDnptyT.jpg",
      type: "movie",
      genres: ["Ação", "Comédia", "Ficção científica"],
      synopsis: "Wade Wilson labuta na vida civil com seus dias como o mercenário Deadpool para trás. Mas precisa convencer Wolverine a ajudá-lo.",
      year: 2024,
      rating: "18",
      duration: "2h 08m",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/movie/533535",
    },
    {
      id: 1022789,
      tmdbId: 1022789,
      title: "DIVERTIDA MENTE 2",
      imageUrl: "https://image.tmdb.org/t/p/w500/lHKNS35r4RTa9GO72vdadMLxoiV.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/p5ozvmdgsmbWe0H8Xk7Rc8SCwAB.jpg",
      type: "movie",
      genres: ["Animação", "Família", "Aventura"],
      synopsis: "Com a chegada da adolescência de Riley, a sala de controle mental passa por uma demolição para dar espaço a novas emoções.",
      year: 2024,
      rating: "L",
      duration: "1h 36m",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/movie/1022789",
    }
  ],
  "Max": [
    {
      id: 94997,
      tmdbId: 94997,
      title: "A CASA DO DRAGÃO",
      imageUrl: "https://image.tmdb.org/t/p/w500/oKJDm4QCKbp6mR4FnxXrFlPJP8Y.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/577eXC8wFQT0eUrJcgznSiFPRmk.jpg",
      type: "series",
      genres: ["Drama", "Ação", "Fantasia"],
      synopsis: "Duzentos anos antes dos eventos de Game of Thrones, a dinastia Targaryen governa Westeros no auge de seu poder com mais de 15 dragões sob seu comando.",
      year: 2024,
      rating: "18",
      duration: "2 Temporadas",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/94997/1/1",
    },
    {
      id: 100088,
      tmdbId: 100088,
      title: "THE LAST OF US",
      imageUrl: "https://image.tmdb.org/t/p/w500/el1KQzwdIm17I3A6cYPfsVIWhfX.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/lY2DhbA7Hy44fAKddr06UrXWWaQ.jpg",
      type: "series",
      genres: ["Drama", "Ação", "Ficção científica"],
      synopsis: "Vinte anos após uma pandemia de fungos destruir a civilização, Joel é contratado para contrabandear Ellie para fora de uma zona de quarentena opressiva.",
      year: 2023,
      rating: "18",
      duration: "1 Temporada",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/100088/1/1",
    },
    {
      id: 1399,
      tmdbId: 1399,
      title: "GAME OF THRONES",
      imageUrl: "https://image.tmdb.org/t/p/w500/aqomTRKjNZkmNEeOZnEmWrFTmKU.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg",
      type: "series",
      genres: ["Drama", "Fantasia", "Ação"],
      synopsis: "Várias famílias nobres disputam o controle do Trono de Ferro de Westeros enquanto uma antiga ameaça ressurge no Norte.",
      year: 2019,
      rating: "18",
      duration: "8 Temporadas",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/tvshow/1399/1/1",
    },
    {
      id: 87108,
      tmdbId: 87108,
      title: "CHERNOBYL",
      imageUrl: "https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/900tHlUYUkp7Ol04XFSoAaEIXcT.jpg",
      type: "series",
      genres: ["Drama", "História"],
      synopsis: "Em 1986, uma enorme explosão na Usina Nuclear de Chernobyl desencadeia um dos piores desastres causados pelo homem.",
      year: 2019,
      rating: "16",
      duration: "Minissérie",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/tvshow/87108/1/1",
    },
    {
      id: 1104,
      tmdbId: 1104,
      title: "MAD MEN",
      imageUrl: "https://image.tmdb.org/t/p/w500/wa7b51oQx1cFPUEMpNsb4b4c6Lu.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/eYDTiJ88jfMJ5Vp3a0OAEihBzZX.jpg",
      type: "series",
      genres: ["Drama"],
      synopsis: "O mundo implacável da publicidade na Nova York dos anos 1960 através dos olhos de Don Draper.",
      year: 2015,
      rating: "16",
      duration: "7 Temporadas",
      match: 94,
      playerUrl: "https://v1.watchplay.shop/tvshow/1104/1/1",
    },
    {
      id: 693134,
      tmdbId: 693134,
      title: "DUNA: PARTE DOIS",
      imageUrl: "https://image.tmdb.org/t/p/w500/8LJJjLjAzAwXS40S5mx79PJ2jSs.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/eZ239CUp1d6OryZEBPnO2n87gMG.jpg",
      type: "movie",
      genres: ["Ficção científica", "Aventura"],
      synopsis: "Paul Atreides se une a Chani e aos Fremen enquanto busca vingança contra os conspiradores que destruíram sua família.",
      year: 2024,
      rating: "14",
      duration: "2h 46m",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/movie/693134",
    }
  ],
  "Prime Video": [
    {
      id: 76479,
      tmdbId: 76479,
      title: "THE BOYS",
      imageUrl: "https://image.tmdb.org/t/p/w500/in1R2dDc421JxsoRWaIIAqVI2KE.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/n6vVs6z8obNbExdD3QHTr4Utu1Z.jpg",
      type: "series",
      genres: ["Ação", "Comédia", "Ficção científica"],
      synopsis: "Uma visão irreverente sobre o que acontece quando super-heróis abusam de seus poderes. Um grupo de vigilantes se une para expor a verdade.",
      year: 2024,
      rating: "18",
      duration: "4 Temporadas",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/tvshow/76479/1/1",
    },
    {
      id: 84773,
      tmdbId: 84773,
      title: "O SENHOR DOS ANÉIS: OS ANÉIS DE PODER",
      imageUrl: "https://image.tmdb.org/t/p/w500/b5pl6GmQmTCHmZKEBhXPN0gmoAq.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/o2wg8QiSCQrhj91tBfxunE3O5Ba.jpg",
      type: "series",
      genres: ["Fantasia", "Aventura", "Ação"],
      synopsis: "Ambientada na Segunda Era da Terra-média, a série acompanha personagens que enfrentam o ressurgimento do mal.",
      year: 2024,
      rating: "14",
      duration: "2 Temporadas",
      match: 91,
      playerUrl: "https://v1.watchplay.shop/tvshow/84773/1/1",
    },
    {
      id: 106379,
      tmdbId: 106379,
      title: "FALLOUT",
      imageUrl: "https://image.tmdb.org/t/p/w500/tQRX6GbYooU7kUaarKf5YXDTONy.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/coaPCIqQBPUZsOnJcWZxhaORcDT.jpg",
      type: "series",
      genres: ["Ficção Científica", "Ação", "Aventura"],
      synopsis: "Em um futuro pós-apocalíptico de Los Angeles devastada por guerra nuclear, os cidadãos precisam viver em bunkers subterrâneos para se proteger.",
      year: 2024,
      rating: "18",
      duration: "1 Temporada",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/tvshow/106379/1/1",
    },
    {
      id: 95557,
      tmdbId: 95557,
      title: "INVENCÍVEL (INVINCIBLE)",
      imageUrl: "https://image.tmdb.org/t/p/w500/qhb7RWU9ad9a5m3HbeRRXzjaMXf.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/9qrroces8C6R9aKr08hACNPVXdZ.jpg",
      type: "series",
      genres: ["Animação", "Ação", "Ficção Científica"],
      synopsis: "Mark Grayson é um adolescente normal, exceto pelo fato de seu pai ser o super-herói mais poderoso do planeta.",
      year: 2024,
      rating: "18",
      duration: "2 Temporadas",
      match: 96,
      playerUrl: "https://v1.watchplay.shop/tvshow/95557/1/1",
    },
    {
      id: 92830,
      tmdbId: 92830,
      title: "REACHER",
      imageUrl: "https://image.tmdb.org/t/p/w500/dnHP6MdJ4jMZgKvNrOYTjrgqn9l.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/p3Jmm6d1ShUrJEuU3DYD2K19c66.jpg",
      type: "series",
      genres: ["Ação", "Crime", "Drama"],
      synopsis: "Jack Reacher, um veterano investigador da polícia militar, entra na vida civil como um andarilho, sem telefone e sem pertences.",
      year: 2023,
      rating: "16",
      duration: "2 Temporadas",
      match: 95,
      playerUrl: "https://v1.watchplay.shop/tvshow/92830/1/1",
    }
  ],
  "Apple TV+": [
    {
      id: 125988,
      tmdbId: 125988,
      title: "SILO",
      imageUrl: "https://image.tmdb.org/t/p/w500/tVR4q9FazxJuCEpaYxiCijUlvM3.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/4XccmjsOmQZw8S2iW1wvlvmb5v1.jpg",
      type: "series",
      genres: ["Ficção científica", "Drama", "Mistério"],
      synopsis: "Em um futuro tóxico e em ruínas, milhares vivem em um silo subterrâneo gigante. Após mortes misteriosas, Juliette começa a desvendar segredos chocantes.",
      year: 2024,
      rating: "16",
      duration: "2 Temporadas",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/tvshow/125988/1/1",
    },
    {
      id: 93740,
      tmdbId: 93740,
      title: "RUPTURA (SEVERANCE)",
      imageUrl: "https://image.tmdb.org/t/p/w500/6qRIQqWwnxVemvvDfFuK3kkIqpS.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/7NNNXo0qG2SqH4JoG7GPvJ2hzes.jpg",
      type: "series",
      genres: ["Drama", "Mistério", "Ficção científica"],
      synopsis: "Mark lidera funcionários cujas memórias foram divididas entre a vida profissional e pessoal, até que um mistério explode na empresa.",
      year: 2025,
      rating: "16",
      duration: "2 Temporadas",
      match: 99,
      playerUrl: "https://v1.watchplay.shop/tvshow/93740/1/1",
    },
    {
      id: 97546,
      tmdbId: 97546,
      title: "TED LASSO",
      imageUrl: "https://image.tmdb.org/t/p/w500/uRHsiw1wLxPHFXkkv4Ix1s0O6f4.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/4bG49jVR7NrCNQjahDUsDqvIwle.jpg",
      type: "series",
      genres: ["Comédia", "Drama"],
      synopsis: "Um técnico americano de futebol americano é contratado para treinar um time de futebol inglês na Premier League.",
      year: 2023,
      rating: "14",
      duration: "3 Temporadas",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/97546/1/1",
    },
    {
      id: 93741,
      tmdbId: 93741,
      title: "FUNDAÇÃO (FOUNDATION)",
      imageUrl: "https://image.tmdb.org/t/p/w500/kClnDGBEXkiiXK5IZ1BY0VgoPhK.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/4WIglfr4lDFVjCEcXzCeu6cJsOh.jpg",
      type: "series",
      genres: ["Ficção Científica", "Drama"],
      synopsis: "Baseado nos romances de Isaac Asimov, um bando de exilados em sua monumental jornada para salvar a humanidade e reconstruir a civilização.",
      year: 2023,
      rating: "14",
      duration: "2 Temporadas",
      match: 94,
      playerUrl: "https://v1.watchplay.shop/tvshow/93741/1/1",
    },
    {
      id: 90282,
      tmdbId: 90282,
      title: "THE MORNING SHOW",
      imageUrl: "https://image.tmdb.org/t/p/w500/y9x2R87yt2U616736NJrP0d56dt.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/uMsTtNaUEWOE2q64m8zthBIMgen.jpg",
      type: "series",
      genres: ["Drama"],
      synopsis: "Uma visão sem filtros dos bastidores dos noticiários matinais mais famosos dos Estados Unidos.",
      year: 2023,
      rating: "16",
      duration: "3 Temporadas",
      match: 93,
      playerUrl: "https://v1.watchplay.shop/tvshow/90282/1/1",
    }
  ],
  "Globoplay": [
    {
      id: 196421,
      tmdbId: 196421,
      title: "OS OUTROS",
      imageUrl: "https://image.tmdb.org/t/p/w500/qXeqUSGQi7Ld91t1xpJGy12laY7.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/lfUPe1AlBcjTLYER6bxkBOhDJ8F.jpg",
      type: "series",
      genres: ["Drama", "Suspense"],
      synopsis: "Dois casais vizinhos entram em choque após a briga de seus filhos em um condomínio fechado na Barra da Tijuca, desencadeando consequências absurdas.",
      year: 2023,
      rating: "16",
      duration: "2 Temporadas",
      match: 98,
      playerUrl: "https://v1.watchplay.shop/tvshow/196421/1/1",
    },
    {
      id: 73010,
      tmdbId: 73010,
      title: "SOB PRESSÃO",
      imageUrl: "https://image.tmdb.org/t/p/w500/lGWf1lqeHOhuKZX9bQPeAKttxnb.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/sql1v8szmHZNPCRfNhSwNpMqOnn.jpg",
      type: "series",
      genres: ["Drama", "Médico"],
      synopsis: "A rotina de entrega, esforço e pressão pela qual os médicos de um hospital público no subúrbio passam todos os dias, arriscando tudo para salvar vidas.",
      year: 2022,
      rating: "16",
      duration: "5 Temporadas",
      match: 97,
      playerUrl: "https://v1.watchplay.shop/tvshow/73010/1/1",
    },
    {
      id: 67535,
      tmdbId: 67535,
      title: "JUSTIÇA",
      imageUrl: "https://image.tmdb.org/t/p/w500/2Jit3hR4CY4LrU06fiLdF0L7SPS.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/dY24bRRqvSjOacyV127z35j2gKv.jpg",
      type: "series",
      genres: ["Drama", "Crime"],
      synopsis: "Traição, desejo de vingança, assassinatos e armações são alguns dos temas de quatro histórias nas quais há sempre um dilema moral envolvido.",
      year: 2024,
      rating: "18",
      duration: "2 Temporadas",
      match: 96,
      playerUrl: "https://v1.watchplay.shop/tvshow/67535/1/1",
    },
    {
      id: 194606,
      tmdbId: 194606,
      title: "RENSGA HITS!",
      imageUrl: "https://image.tmdb.org/t/p/w500/3JA7HYJ7TS9y4MY5um1cws9mzIx.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/mVMlieapNYCBCH53rM46mAi3DMR.jpg",
      type: "series",
      genres: ["Comédia", "Drama", "Música"],
      synopsis: "Jovem cantora se muda para Goiânia em busca do sonho de ser uma estrela de sucesso e acaba descobrindo os bastidores da indústria sertaneja.",
      year: 2024,
      rating: "14",
      duration: "2 Temporadas",
      match: 94,
      playerUrl: "https://v1.watchplay.shop/tvshow/194606/1/1",
    },
    {
      id: 112468,
      tmdbId: 112468,
      title: "AS FIVE",
      imageUrl: "https://image.tmdb.org/t/p/w500/3vWANjNHJvgkwBzE2x6kWOiKSXo.jpg",
      backdropUrl: "https://image.tmdb.org/t/p/original/70adcDcYqa2EFrhoD0TfOFmqjkJ.jpg",
      type: "series",
      genres: ["Comédia", "Drama"],
      synopsis: "Keyla, Ellen, Lica, Tina e Benê se reencontram após seis anos. Na transição para a vida adulta, enfrentam os desafios de suas carreiras e afetos.",
      year: 2024,
      rating: "16",
      duration: "3 Temporadas",
      match: 93,
      playerUrl: "https://v1.watchplay.shop/tvshow/112468/1/1",
    }
  ]
};

